### ISSUE TITLE
Are there any plans for the cgi response?

### ISSUE THREAD

**Issue by huyanping** [lisachenko/protocol-fcgi#6]

**Comment by lisachenko** [comment]
Hi, could you please elaborate more about what do you want to get? This repo contains all low-level primitives for FCGI protocol, both for request and response API.

**Comment by huyanping** [comment]
Thanks for your attention. I want to create an CGI response object, but I did not found the way.
I have read the demos in `readme.md`. In the first example a socket client create an request object and sent it to the server. In the second example a socket server receive a request object. But there is no example about how to create a response object.

**Comment by AndrewCarterUK** [comment]
@huyanping - You would need to respond by writing [STDOUT records](https://github.com/lisachenko/protocol-fcgi/blob/master/src/FCGI/Record/Stdout.php) down the socket.

This library is an implementation of the FastCGI protocol - because of this, it can be used in a FastCGI client or server, but it does not directly implement either of these roles itself.

If you want to learn a bit about FastCGI protocol, I'd recommend using this library to build your own FastCGI server. You'll be able to tailor it exactly to your requirements and learn a load in the process. If you're looking for a ready to use PHP FastCGI server library, I've written one called [PHPFastCGI](https://github.com/PHPFastCGI/FastCGIDaemon) which you may find useful (even as a reference).

**Comment by lisachenko** [comment]
@huyanping now your question is clear ) As you can see in previous message, @AndrewCarterUK have already described that you need to respond via Stdout records.

Here is typical example of raw communication via FCGI:
```
{FCGI_BEGIN_REQUEST,   1, {FCGI_RESPONDER, 0}}
{FCGI_PARAMS,          1, "\013\002SERVER_PORT80\013\016SER"}
{FCGI_PARAMS,          1, "VER_ADDR199.170.183.42 ... "}
{FCGI_PARAMS,          1, ""}
{FCGI_STDIN,           1, "quantity=100&item=3047936"}
{FCGI_STDIN,           1, ""}

    {FCGI_STDOUT,      1, "Content-type: text/html\r\n\r\n<html>\n<head> ... "}
    {FCGI_STDOUT,      1, ""}
    {FCGI_END_REQUEST, 1, {0, FCGI_REQUEST_COMPLETE}}
```

As you can see, after reading some information from request and stdin, we sending our stdout, then one more empty stdout record (it's termination mark) and one more special record for finishing our request.

Implementation can be like this:
```php
    $messages = [
        new Record\Stdout('Some content....'),
        new Record\Stdout(),
        new Record\EndRequest()
    ];
    $packet = join('', $messages);
    fwrite($phpSocket, $packet);
```

I think, I'll add full-featured client to this library to simplify the library usage. Because protocol knowledge is not required for most use cases.

**Comment by huyanping** [comment]
I wrote a demo program([swoole-php-fpm](https://github.com/huyanping/swoole-php-fpm)) and run it under nginx server. Then I got HTTP 504.
```php
    public function handle(Record $record)
    {
        var_dump($record);
        $messages = array(
            new Record\Stdout("Content-type: text/html\r\n\r\nHello world"),
            new Record\Stdout(),
            new Record\EndRequest(),
        );

        return join('', $messages);
    }
```
The out put is:
```
php examples/php-fpm.php
object(Protocol\FCGI\Record\BeginRequest)#10 (11) {
  ["role":protected]=>
  int(1)
  ["flags":protected]=>
  int(0)
  ["reserved1":protected]=>
  string(5) ""
  ["version":protected]=>
  int(1)
  ["type":protected]=>
  int(1)
  ["requestId":protected]=>
  int(1)
  ["reserved":protected]=>
  int(0)
  ["contentLength":"Protocol\FCGI\Record":private]=>
  int(8)
  ["paddingLength":"Protocol\FCGI\Record":private]=>
  int(0)
  ["contentData":"Protocol\FCGI\Record":private]=>
  string(8) ""
  ["paddingData":"Protocol\FCGI\Record":private]=>
  string(0) ""
}
string(72) "&Content-type: text/html

Hello worl" 
```

**Comment by lisachenko** [comment]
Hi, I looked into your code and discovered some issues:

- You are trying to read a request as a single packet (if hasFrame() then immediately handle it and write a response). It's not correct, because you should receive a sequence of frames: BEGIN_REQUEST, PARAMS, PARAMS(empty one), N*STDIN packets and only after that you should write a response back to the NGINX.
- In my example I had a mistake, your need to write the correct request identifier for each packet. Your should take this information from the BEGIN_REQUEST message. And write it to all response messages:
```php
        foreach ($messages as $message) {
            $message->setRequestId($requestId);
        }
```

BTW, have you seen the documentation about FCGI www.mit.edu/~yandros/doc/specs/fcgi-spec.html? It contains nice examples of packets. It can be easier to read it before writing a code, but I have a confidence that these low-level details of transport protocol should be wrapped into the high-level client, because these details should not be visible from the outside.

**Comment by AndrewCarterUK** [comment]
The data sent in the records sent is wrong, needs to me more like this:

```
Status: 200\r\n
Header: value\r\n
Header: value\r\n
\r\n
Message...
```

**Comment by huyanping** [comment]
I sent this to the nginx server, but I still got a 502 error.
```php
        $data = "Status: 200\r\n
Server: X2S_Platform\r\n
Connection: keep-alive\r\n
Date: Tue, 08 Nov 2016 08:22:43 GMT\r\n
Cache-Control: max-age=2592000\r\n
Expires: Thu, 08 Dec 2016 08:22:43 GMT\r\n
Last-Modified: Mon, 07 Nov 2016 11:35:21 GMT\r\n
Content-Type: image/jpeg\r\n
Content-Length: {$length}\r\n
Keep-Alive: timeout=60\r\n
X-Cache-Lookup: Hit From Disktank\r\n\r\n" . $body;
```

**Comment by lisachenko** [comment]
@AndrewCarterUK

**Comment by lisachenko** [comment]
Could you add please more details from the nginx error log?

**Comment by huyanping** [comment]
This is the error message. Looks like I didn't sent the request id back to the nginx server.
```
2016/11/08 16:37:31 [error] 3506#0: *52746735 upstream sent unexpected FastCGI request id low byte: 0 while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: php-fpm.huyanping.cn, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "my.domain"
```

**Comment by lisachenko** [comment]
Ok, error message clearly states, that we didn't match with requestID from the request. Have you implemented this:
>  In my example I had a mistake, your need to write the correct request identifier for each packet. Your should take this information from the BEGIN_REQUEST message. And write it to all response messages:

        foreach ($messages as $message) {
            $message->setRequestId($requestId);
        }

**Comment by lisachenko** [comment]
I definitely should write a high-level client for this library, hope I can found enough free time to prepare it for you. For the moment, knowing FCGI protocol details is required to use this library properly.

**Comment by huyanping** [comment]
I find another error. The nginx server is waiting for something until I kill my php-fpm process. I guess that the nginx think the data is not complete.

That's a great idea. Actually I am trying to write a php-fpm server based on this package and extension swoole, but I there are some problems that I can not solve.

**Comment by huyanping** [comment]
The code is here: [example](https://github.com/huyanping/swoole-php-fpm/blob/master/src/Handler/EchoHandler.php). And I have pushed every commits.

**Comment by lisachenko** [comment]
Hi, @huyanping here is my simple working example https://gist.github.com/lisachenko/825e1042b7152c3fc32f655b7e818e8f

Just dirty implementation.

**Comment by huyanping** [comment]
Hi @lisachenko @AndrewCarterUK ,I have update my code and it works. I will learn about cgi protocol and try to write a stable php-fpm server based on this package. Thank you so much for your help.

**Comment by lisachenko** [comment]
@huyanping you are welcome )
